// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ??
  "https://iucshpgbiudumeehbeyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1Y3NocGdiaXVkdW1lZWhiZXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5MzUwMjUsImV4cCI6MjA5MjUxMTAyNX0.fQbwl5GoQNXIQT88S-2PNHEPnfSI7EtbpXBQs2ccLd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);